### PR TITLE
DNSPOD & ADGUARD

### PR DESCRIPTION
**Pull request by BirdInFire**
To close issue : 
https://github.com/paulmillr/encrypted-dns/issues/54
and issue : 
https://github.com/paulmillr/encrypted-dns/issues/37

### CODE REVIEW

**Comment by paulmillr** [comment]
Why did you change to 🔴?

**Comment by BirdInFire** [comment]
normal adguard filter ads no ? I was thinking the green is only for unfiltered dns ? (maybe I'm wrong)

**Comment by BirdInFire** [comment]
go to : https://adguard.com/en/adguard-dns/overview.html you will see before unfiltered : 
"Please note: the "Non-filtering" DNS servers provide a secure and reliable connection, but they don't filter anything like the "Default" and "Family protection" servers do. Please don't use them unless you know what you're doing."

**Comment by BirdInFire** [comment]
Updated my pull request with you change (know issue).

**Comment by BirdInFire** [comment]
@paulmillr if I can do anything else for this PR tell me ^^

**Comment by paulmillr** [comment]
Where was 162.14.21.56 taken from? Point me to official URL

**Comment by BirdInFire** [comment]
I have récuperated them from the https profile but after your remark and some search : https://kb.adguard.com/en/general/dns-providers#dnspod-dns its seem they are indeed false I have modified both TLS and HTTPS for comply with these IP

**Pull request merged**
