### PR TITLE
[Maintenance] Re-Sign all profiles

### PR DESCRIPTION
**Pull request by Xernium**
All profiles were re-signed with https://crt.sh/?id=15172262479
Profiles will be re-signed upon request or in 11 months

Additionally, README was modified

### CODE REVIEW

**Comment by Xernium** [comment]
> It would be great and more secure if there was a simple way to verify the files are equal between signed / unsigned versions. From what I understand the only real difference is header / footer which contain signatures. The content in the middle is the same.

I'm happy to provide signature files over hashes to prove this; but that's sadly rather hard to verify

**Comment by paulmillr** [comment]
I think we can make a simple script that checks binary diffs while skipping signatures!

**Comment by Xernium** [comment]
While we are at it, I should probably also attach the script I wrote to automatically sign the profiles.
If you know of a way to do it outside of macOS (without using the security cli tool) I'm also open to that

**Comment by hritvikpatel4** [comment]
Isn't it possible using GitHub Actions? What if we use the macOS build agent?

**Comment by paulmillr** [comment]
https://github.com/paulmillr/encrypted-dns/issues/158

**Pull request merged**
