### PR TITLE
add DNSpod

### PR DESCRIPTION
**Pull request by Silentely**

### CODE REVIEW

**Comment by Silentely** [comment]
add DNSpod andAdguard 
AdGuard DNS profile — blocks ads, tracking, malicious and phishing websites.
AdGuard DNS Non-filtering profile — doesn't block or censor anything. Use it if you just need a fast and zero logging DNS service.

**Comment by paulmillr** [comment]
Thanks!

**Comment by paulmillr** [comment]
Seems like something is wrong with AdGuard. The files are "binary" and 5kb. Others files in the repo including dnspod are 1kb.

**Comment by Silentely** [comment]
Yes, this is an official description file that contains signature information. The official page is here https://adguard.com/en/blog/encrypted-dns-ios-14.html

**Comment by paulmillr** [comment]
We don't need "signed" profiles. This repo only contains unsigned ones. 

Signed profiles cannot be audited easily.

**Comment by Silentely** [comment]
OK, I have deleted it and only keep dnspod

**Pull request merged**
