### PR TITLE
Signed the mobileconfigs

### PR DESCRIPTION
**Pull request by Candygoblen123**
I've signed the mobileconfig files with my developer ID, so that the red "Not Signed" warning will not appear when adding the certificate.

### CODE REVIEW

**Comment by paulmillr** [comment]
Hi

That's alright, but the idea behind unsigned configs was that it's easy to verify. We cannot verify these. 

Can you move all your stuff into "signed" dir?

**Comment by Candygoblen123** [comment]
I'm not sure what you mean when you say you cannot verify these. Signing them adds a signature to the file, and you should still be able to open it in a text editor to look at the plist file, which remains intact, albeit with a little bit of scrambled characters added to the top and bottom of the files.  However, I will move the signed files to a subdirectory when I have time later.

**Comment by paulmillr** [comment]
I didn't know that.

Can you add a clarification about what `signed` dir is for to readme? That will do it.

**Comment by Candygoblen123** [comment]
That sounds good to me, but I am going to add a note that the signed files are signed by a third party, and that they may lag behind the unsigned versions a little bit.

**Comment by Candygoblen123** [comment]
I also put in a commented out line saying that we recommend installing the signed versions, and you can choose to include it if you want.

**Comment by paulmillr** [comment]
Thanks

**Pull request merged**
